software-mansion/react-native-executorch

- android/src/main/java/com/rnexecutorch/RnExecutorchModule.kt
> chore: update RnExecutorchModule.kt

- android/build.gradle
- jitpack.yml
- pom.xml
> Host executorch.aar file on jitpack

- react-native-executorch.podspec
Pod: https://github.com/software-mansion-labs/opencv-rne
> Add OpenCV dependency for iOS

- examples/computer-vision/models/style_transfer.ts
- examples/computer-vision/screens/StyleTransferScreen.tsx
- src/constants/modelUrls.ts
Style transfer models are now fetched from hf repository, depending on device OS it's using coreml or xnnpack model, also binary files were removed from example app
> chore: Style transfer models uploaded to hf repo

- examples/computer-vision/models/classification.ts
- examples/computer-vision/screens/ClassificationScreen.tsx
- src/constants/modelUrls.ts
Use classification models from Hugging Face
> Use Hugging Face classification models

- docs/docs/module-api/executorch-bindings.md
> docs: fix broken link

- docs/docs/module-api/executorch-bindings.md
> fix: docs typo

- examples/computer-vision/App.tsx
- examples/computer-vision/package.json
- examples/computer-vision/yarn.lock
- examples/llama/ios/Podfile.lock
- examples/llama/package.json
- examples/llama/yarn.lock
- package.json
> Bump verison

- examples/computer-vision/yarn.lock
- examples/llama/yarn.lock
> Generate lock file

- docs/docs/llms/exporting-llama.mdx
- docs/src/css/colors.css
- docs/src/pages/index.tsx
- docs/src/theme/TOCItems/index.js
- docs/src/theme/TOCItems/index.tsx
- docs/src/theme/TOCItems/styles.module.css
Landing Page text changes, docs color changes
> docs: Improvements

- docs/src/css/colors.css
> Update admonitions colors

- lefthook.yml
> chore: Add lefthook back

- docs/docs/module-api/executorch-bindings.md
Correct link in ExecuTorch bindings documentation
> fix: Correct link in ExecuTorch bindings documentation

- docs/docs/hookless-api/SpeechToTextModule.md
> fix: edit docs link

- README.md
> docs(readme): fix readme quickstart typo

- docs/docs/llms/useLLM.md
There was a small typo in the `useLLM` example code snippet
It's nice to be able to copy-paste snippets from the docs
> add missing curly braces to example code snippet

- README.md
> docs: update README with Product Hunt badge

- src/utils/fetchResource.ts
> fix: handle local files

- examples/computer-vision/App.tsx
- examples/computer-vision/ios/Podfile.lock
- examples/computer-vision/package.json
- examples/computer-vision/screens/ImageSegmentationScreen.tsx
- examples/computer-vision/yarn.lock
- src/constants/modelUrls.ts
Add image segmentation example to computer vision app.
> feat: Add image segmentation example

- examples/computer-vision/ios/Podfile.lock
- examples/computer-vision/yarn.lock
- examples/llama/ios/Podfile.lock
- examples/llama/yarn.lock
- examples/speech-to-text/ios/Podfile.lock
- examples/speech-to-text/package.json
- examples/speech-to-text/yarn.lock
Bump version in all example apps to 0.3.2
> chore:bump version to 0.3.2 in examples

- .github/workflows/docs-build-check.yml
> ci: fix docs build check workflow failing on node post setup 

- android/src/main/java/com/swmansion/rnexecutorch/Tokenizer.kt
- ios/ExecutorchLib.xcframework/ios-arm64-simulator/ExecutorchLib.framework/Headers/HuggingFaceTokenizer.h
- ios/ExecutorchLib.xcframework/ios-arm64-simulator/ExecutorchLib.framework/_CodeSignature/CodeResources
- ios/ExecutorchLib.xcframework/ios-arm64/ExecutorchLib.framework/Headers/HuggingFaceTokenizer.h
- ios/ExecutorchLib.xcframework/ios-arm64/ExecutorchLib.framework/_CodeSignature/CodeResources
- ios/RnExecutorch/Tokenizer.mm
- src/native/NativeTokenizer.ts
- third-party/ios/ExecutorchLib/ExecutorchLib/Exported/HuggingFaceTokenizer.h
- third-party/ios/ExecutorchLib/ExecutorchLib/Exported/HuggingFaceTokenizer.mm
This PR adds skipSpecialTokens flag to argument list of decode method
> feat: add option to pass skip special tokens flag to decode

- .github/workflows/build-android-llama-example.yml
- .github/workflows/build-ios-llama-example.yml
- .github/workflows/ci.yml
- .github/workflows/docs-build-check.yml
- .github/workflows/publish_docs.yml
This PR will allow to manually run the workflows we currently have 👍🏻
> ci: enable manual workflows triggering

- react-native-executorch.podspec
Change the pod source in podspec to Software Mansion repo.
> chore: change the source in podspec

- android/src/main/java/com/swmansion/rnexecutorch/Tokenizer.kt
- ios/RnExecutorch/Tokenizer.mm
- src/Error.ts
- src/hooks/natural_language_processing/useTokenizer.ts
- src/index.tsx
- src/modules/natural_language_processing/TokenizerModule.ts
- src/native/NativeTokenizer.ts
> feat: Add tokenizer

- docs/docs/natural-language-processing/useLLM.md
- docs/docs/natural-language-processing/useTokenizer.md
- docs/docs/typescript-api/ClassificationModule.md
- docs/docs/typescript-api/ExecutorchModule.md
- docs/docs/typescript-api/ImageSegmentationModule.md
- docs/docs/typescript-api/LLMModule.md
- docs/docs/typescript-api/OCRModule.md
- docs/docs/typescript-api/ObjectDetectionModule.md
- docs/docs/typescript-api/SpeechToTextModule.md
- docs/docs/typescript-api/StyleTransferModule.md
- docs/docs/typescript-api/TextEmbeddingsModule.md
- docs/docs/typescript-api/TokenizerModule.md
- docs/docs/typescript-api/VerticalOCRModule.md
> docs: Add tokenizer documentation

- docs/docs/natural-language-processing/useLLM.md
- examples/llm-tool-calling/src/components/MessageItem.tsx
- examples/llm-tool-calling/src/components/Messages.tsx
- examples/llm-tool-calling/src/screens/ChatScreen.tsx
- examples/llm-tool-calling/src/screens/tools.ts
- examples/llm/App.tsx
- examples/llm/components/MessageItem.tsx
- examples/llm/components/Messages.tsx
- examples/llm/screens/ChatScreen.tsx
- src/controllers/LLMController.ts
- src/hooks/natural_language_processing/useLLM.ts
- src/types/llm.ts
Add method for deleting the message and all following messages. I've also modified the example so it showcases the feature:
[](https://github.com/user-attachments/assets/bf13746d-9628-4512-a27a-cd9532e01f44)
#206
> feat: Delete message functionality in useLLM

- docs/docs/natural-language-processing/useLLM.md
- examples/llm/screens/ChatScreen.tsx
- src/constants/modelUrls.ts
The PR adds urls to new models:
- qwen 3 (3 sizes, quantized and unquantized)
- qwen 2.5 (3 sizes, quantized and unquantized)
- phi 4 mini (1 size, quantized and unquantized)
- hammer 2.1 (3 sizes, quantized and unquantized)
- smollm2 (3 sizes, quantized and unquantized)
Repositories on hf are configured and tags are added.
> feat: add urls for qwen 3 and other models(quantized and unquantized)

- package.json
- yarn.lock
> chore:HF/jinja update

- examples/computer-vision/ios/Podfile.lock
- examples/computer-vision/yarn.lock
- examples/llm-tool-calling/ios/Podfile.lock
- examples/llm-tool-calling/package.json
- examples/llm-tool-calling/src/screens/ChatScreen.tsx
- examples/llm-tool-calling/yarn.lock
- examples/llm/ios/Podfile.lock
- examples/llm/package.json
- examples/llm/yarn.lock
- examples/speech-to-text/ios/Podfile.lock
- examples/speech-to-text/package.json
- examples/speech-to-text/screens/SpeechToTextScreen.tsx
- examples/speech-to-text/yarn.lock
- examples/text-embeddings/package.json
- examples/text-embeddings/yarn.lock
This PR updates versions of dependent packages and fixes the problem with Tokenizers not working on android.
> chore: bump audio api version and fix problem with tokenizers

- examples/llm/screens/LLMScreen.tsx
- examples/llm/screens/LLMToolCallingScreen.tsx
> fix: Disable autocorrect in TextInput within LLM demo app 

- src/hooks/computer_vision/useOCR.ts
- src/hooks/computer_vision/useVerticalOCR.ts
- src/hooks/natural_language_processing/useSpeechToText.ts
> fix: Controller initialization in ocr and s2t hooks

- .cspell-wordlist.txt
- docs/docs/benchmarks/inference-time.md
- docs/docs/benchmarks/memory-usage.md
- docs/docs/benchmarks/model-size.md
- docs/docs/natural-language-processing/useTextEmbeddings.md
Changes:
1. Add text embedding models benchmarks
2. Add new text embedding models to docs
3. Add text embedding models descriptions
> docs: Add text embeddings benchmarks

- src/controllers/LLMController.ts
> fix: Added isReady check to generate

- examples/llm/App.tsx
- src/controllers/SpeechToTextController.ts
Small bug fix, typo in example app
> bug:s2t fix

- README.md
> Fix examples section in readme

- package.json
- yarn.lock
Bump expo file system and expo asset
> chore: Bump expo file system and expo asset

- docs/docs/computer-vision/useOCR.md
- docs/docs/typescript-api/ImageSegmentationModule.md
- docs/docs/typescript-api/OCRModule.md
Fix some issues in our documentation.
> chore: Update docs

- package.json
> chore: bump library version in package.json to v0.4.0 👀 

- .github/workflows/publish_docs.yml
> fix: Docs should only publish on pushes to main with docs path.

- package.json
> Bump to version to 0.4.1

- examples/computer-vision/ios/Podfile.lock
- examples/computer-vision/package.json
- examples/computer-vision/yarn.lock
- examples/llm/ios/Podfile.lock
- examples/llm/package.json
- examples/llm/yarn.lock
- examples/speech-to-text/ios/Podfile.lock
- examples/speech-to-text/package.json
- examples/speech-to-text/yarn.lock
- examples/text-embeddings/ios/Podfile.lock
- examples/text-embeddings/package.json
- examples/text-embeddings/yarn.lock
> Bump version of the library in example apps

- README.md
> docs: Remove outdated video from README

- .github/workflows/publish_docs.yml
Don't deploy docs on push to main
> chore: don't deploy docs on push to main

- packages/react-native-executorch/src/controllers/LLMController.ts
> fix: Prevent next forward calls when isGenerating=true

- packages/react-native-executorch/src/native/NativeClassification.ts
- packages/react-native-executorch/src/native/RnExecutorchModules.ts
> fix: Remove unnecessary files after adding C++ classification

- .github/workflows/publish_docs.yml
> chore: Publish docs on push to main

- docs/docs/natural-language-processing/useSpeechToText.md
- docs/docs/typescript-api/SpeechToTextModule.md
- docs/versioned_docs/version-0.3.x/hookless-api/SpeechToTextModule.md
- docs/versioned_docs/version-0.3.x/speech-to-text/useSpeechToText.md
- docs/versioned_docs/version-0.4.x/natural-language-processing/useSpeechToText.md
- docs/versioned_docs/version-0.4.x/typescript-api/SpeechToTextModule.md
> docs: fix errors in docs in spoech to text examples

- apps/llm/app/llm/index.tsx
- apps/llm/app/llm_tool_calling/index.tsx
- packages/react-native-executorch/common/runner/runner.cpp
- packages/react-native-executorch/common/runner/text_token_generator.h
Emojis are decoded correctly now! It should also fix issues with Android broken generation!
https://github.com/user-attachments/assets/06b3676a-8fe7-40a2-a38a-65e261bf02a0
#348
> fix: Fixed emoji display in LLM output decoding

- apps/text-embeddings/app/clip-embeddings/index.tsx
- apps/text-embeddings/app/text-embeddings/index.tsx
- docs/docs/natural-language-processing/useTextEmbeddings.md
- docs/docs/typescript-api/TextEmbeddingsModule.md
- packages/react-native-executorch/common/rnexecutorch/models/text_embeddings/TextEmbeddings.cpp
- packages/react-native-executorch/common/rnexecutorch/models/text_embeddings/TextEmbeddings.h
- packages/react-native-executorch/src/constants/modelUrls.ts
- packages/react-native-executorch/src/hooks/natural_language_processing/useTextEmbeddings.ts
- packages/react-native-executorch/src/modules/natural_language_processing/TextEmbeddingsModule.ts
Changes:
- Remove mean pooling from text embeddings postprocessing
- Remove normalization from text embeddings porstprocessing
> refactor: Text Embeddings

- docs/docs/01-fundamentals/01-getting-started.md
- docs/versioned_docs/version-0.1.x/fundamentals/getting-started.mdx
- docs/versioned_docs/version-0.2.x/fundamentals/getting-started.mdx
- docs/versioned_docs/version-0.3.x/fundamentals/getting-started.md
fix docs version changing on mobile phones
> docs: fix docs version changing on mobile phones

- docs/package.json
- docs/yarn.lock
Changes:
- t-rex-ui bump to version 1.0.1
> fix: versions on mobile sidebar not visible

- src/modules/general/ExecutorchModule.ts
Fix Executorchmodule BigInt64Array handling
> fix: Executorchmodule BigInt64Array handling

- packages/react-native-executorch/common/rnexecutorch/Log.h
- packages/react-native-executorch/common/rnexecutorch/tests/LogTest.cpp
As in the title, tiny changes in handling boolean values and added two tests.
Run test with provided scripts and check if they pass
> Setup oss to print bools correctly out-of-the-box & add three tests

- apps/llm/app/llm/index.tsx
> chore: replace QLoRa model with SpinQuant one

- packages/react-native-executorch/src/constants/modelUrls.ts
> fix: update whisper model URLs to use the correct version tag

- packages/react-native-executorch/package.json
Add prepack and postpack scripts to manage README.md
> feat: add prepack and postpack scripts to manage README.md

- README.md
Add Real-World Example section to README
> Add Real-World Example section to README

- packages/react-native-executorch/common/rnexecutorch/RnExecutorchInstaller.cpp
remove comma causing failing builds on android
> remove unneeded comma

- packages/react-native-executorch/package.json
> bump 0.5.4

- packages/react-native-executorch/common/rnexecutorch/models/speech_to_text/SpeechToText.cpp
- packages/react-native-executorch/common/rnexecutorch/models/speech_to_text/SpeechToText.h
- packages/react-native-executorch/common/rnexecutorch/models/speech_to_text/asr/ASR.cpp
- packages/react-native-executorch/common/rnexecutorch/models/speech_to_text/asr/ASR.h
- packages/react-native-executorch/common/rnexecutorch/models/speech_to_text/stream/HypothesisBuffer.cpp
- packages/react-native-executorch/common/rnexecutorch/models/speech_to_text/stream/HypothesisBuffer.h
- packages/react-native-executorch/common/rnexecutorch/models/speech_to_text/stream/OnlineASRProcessor.cpp
- packages/react-native-executorch/common/rnexecutorch/models/speech_to_text/stream/OnlineASRProcessor.h
Changes:
- add missing `<sstream>` include
- update namespace usage
> fix: add sstream include and update namespace usage

- packages/react-native-executorch/common/rnexecutorch/jsi/OwningArrayBuffer.h
- packages/react-native-executorch/common/rnexecutorch/models/BaseModel.cpp
- packages/react-native-executorch/common/rnexecutorch/models/embeddings/BaseEmbeddings.cpp
- packages/react-native-executorch/common/rnexecutorch/models/image_segmentation/ImageSegmentation.cpp
- packages/react-native-executorch/common/rnexecutorch/models/speech_to_text/SpeechToText.cpp
- packages/react-native-executorch/common/rnexecutorch/models/speech_to_text/SpeechToText.h
Adding constructors to `OwningArrayBuffer` that accept data via pointer or vector.
Closes #584
> chore: Extract make owning buffer

- packages/react-native-executorch/common/rnexecutorch/models/speech_to_text/SpeechToText.cpp
- packages/react-native-executorch/common/rnexecutorch/models/speech_to_text/SpeechToText.h
Changes:
- reorder data member declarations
> fix: s2t demo app crashes

- packages/react-native-executorch/android/src/main/cpp/CMakeLists.txt
> chore: small refactor of CMakeLists.txt

- docs/src/components/ReactNativeExecuTorchIntroduction/styles.module.css
- docs/src/components/ReactNativeExecutorchAction/index.tsx
- docs/src/components/ReactNativeExecutorchAction/styles.module.css
- docs/src/pages/styles.module.css
Fixed bug on iphones and safari with svg not displaying properly.
- [] Android
> chore: fixed private mind logo not displaying properly on iphones and safari

- packages/react-native-executorch/android/CMakeLists.txt
- packages/react-native-executorch/android/build.gradle
- packages/react-native-executorch/android/src/main/cpp/CMakeLists.txt
> fix: ensure compatibility with RN > 80
