src/modelUrls.ts
Currently, the model URL points to the main branch on the hugginface repo. Instead, we want to match it with the v0.1.0 version. This PR introduces that change.
=> Update LLaMA model urls with correct versioning

.github/workflows/docs-build-check.yml
Currently, the docs build check action fails. The reason is that setup-node with yarn caching throws an error when yarn cache directory doesn't exist. The action throws an error to prevent saving empty folder, see https://github.com/actions/setup-node/issues/317. This PR is a workaround for that.
=> Fix docs build check post-step 

README.md
This PR adds a minimal Android and iOS versions required to use the library. It also fixes the example app instructions.
=> Add minimal supported versions for iOS & Android

llama_export/build_llama_binary.sh
Currently, in order to use the `build_llama_binary.sh` one needs to build the docker image on their own. This PR changes that. Now the script pulls from GHCR instead.
=> Update build llama binary script to pull from GHCR

.github/workflows/build-ios-llama-example.yml
Added a workflow to build llama example app on iOS.
=> ci: add llama example build (iOS)

android/src/main/java/com/rnexecutorch/Fetcher.kt, ios/utils/LargeFileFetcher.mm
Currently, the HuggingFace download count is not incremented when downloading models. HF counts the model downloads by counting the requests sent to the config.json file in the repository root (a HEAD request is enough). This PR sends a HEAD request to the config json, when the model source is our organization. 
source: https://huggingface.co/docs/hub/models-download-stats
=> Send a request to config.json when downloading model from HF repository

examples/llama/package.json, examples/llama/yarn.lock, package.json
=> chore: bump library version to v0.1.2, bump example llama app to latest minor version

docs/docs/guides/running-llms.md
Hello, i found a wrong link href in [/docs/guides/running-llms](https://docs.swmansion.com/react-native-executorch/docs/guides/running-llms) Running LLMs section. The constants href goes to github's 404 not found page. I fixed this href.
=> Fix wrong link href in docs/running-llms.md

android/src/main/java/com/swmansion/rnexecutorch/ETModule.kt, android/src/main/java/com/swmansion/rnexecutorch/RnExecutorchModule.kt, android/src/main/java/com/swmansion/rnexecutorch/utils/Fetcher.kt, docs/docs/fundamentals/getting-started.mdx
The file loaded from React-Native assets is served in a different way in debug and release mode, for now in release mode it was blocking applications from working
=> fix: wrong handle of assets files in release apk

android/src/main/java/com/swmansion/rnexecutorch/LLM.kt, android/src/main/java/com/swmansion/rnexecutorch/RnExecutorchPackage.kt, ios/RnExecutorch.xcodeproj/project.pbxproj, ios/RnExecutorch/LLM.h, ios/RnExecutorch/LLM.mm, ios/RnExecutorch/RnExecutorch.h, src/LLM.ts, src/index.tsx, src/native/NativeLLM.ts, src/native/RnExecutorchModules.ts
Turbo module which was handling running of llama models was named RnExecutorchModule which wasn't really clear and conflicted with name of library, it's now changed to LLM, matching the style of StyleTransfer, ObjectDetection etc.
=> refactor: change naming of RnExecutorchModule to LLM

package.json, yarn.lock
=> chore: remove redundant dependency

ios/RnExecutorch/utils/Constants.h
There is a missing header for Constants.mm, which causes the build to crash. This PR fixes that by adding the header file
=> fix: Add missing header file

android/src/main/java/com/swmansion/rnexecutorch/Classification.kt, android/src/main/java/com/swmansion/rnexecutorch/ETModule.kt, android/src/main/java/com/swmansion/rnexecutorch/StyleTransfer.kt, android/src/main/java/com/swmansion/rnexecutorch/utils/ETError.kt, docs/docs/guides/running-llms.md, examples/computer-vision/screens/ClassificationScreen.tsx, examples/computer-vision/screens/ObjectDetectionScreen.tsx, examples/computer-vision/screens/StyleTransferScreen.tsx, examples/llama/screens/ChatScreen.tsx, ios/RnExecutorch/models/BaseModel.mm, ios/RnExecutorch/utils/ETError.h, src/ETModule.ts, src/Error.ts, src/StyleTransfer.ts, src/constants/modelUrls.ts, src/models/Classification.ts
Standardize naming and fix urls
=> @jakmro/standardize naming

ios/RnExecutorch/utils/ImageProcessor.mm
Result path returned from style transfer was missing file:// prefix, due to that using style transfered image for other task was throwing error
=> fix: path of result image was missing file:// prefix(ios)

docs/docs/computer-vision/useStyleTransfer.mdx, docs/docs/module-api/executorch-bindings.md
=> docs: fix typo

android/src/main/java/com/swmansion/rnexecutorch/LLM.kt, ios/RnExecutorch/LLM.mm, ios/RnExecutorch/utils/LargeFileFetcher.mm, src/LLM.ts, src/native/NativeLLM.ts
There was a problem when user was switching between multiple llms in one component, to fix this issue I removed code related to handling strict mode problems(strict mode was causing problems with event listeners also so I think we should ignore it as it isn't the best with background tasks), I've also remove deleteModule native function as it wasn't really doing anything, now user can download multiple llms within one component and seamlessly switch between them without bugs.
The problem was mentioned in issue #42
=> fix: issue with isModelGenerating when switching between multiple models

docs/docusaurus.config.js, docs/src/components/ExecuTorchIntroduction/index.tsx, docs/src/components/ExecuTorchIntroduction/styles.module.css, docs/src/components/FooterBackground/index.tsx, docs/src/components/FooterBackground/styles.module.css, docs/src/components/Hero/StartScreen/Logo.tsx, docs/src/components/Hero/StartScreen/index.tsx, docs/src/components/Hero/StartScreen/styles.module.css, docs/src/components/HomepageButton/styles.module.css, docs/src/components/ReactNativeExecuTorchFeatures/ReactNativeExecuTorchFeatureItem/index.tsx, docs/src/components/ReactNativeExecuTorchFeatures/ReactNativeExecuTorchFeatureItem/styles.module.css, docs/src/components/ReactNativeExecuTorchFeatures/ReactNativeExecuTorchFeatureList/index.tsx, docs/src/components/ReactNativeExecuTorchFeatures/ReactNativeExecuTorchFeatureList/styles.module.css, docs/src/components/ReactNativeExecuTorchFeatures/index.tsx, docs/src/components/ReactNativeExecuTorchFeatures/styles.module.css, docs/src/components/Wave/WaveBottom/index.tsx, docs/src/components/Wave/WaveBottom/styles.module.css, docs/src/components/Wave/WaveBottom/wave.tsx, docs/src/components/Wave/WaveBottom/waves.tsx, docs/src/components/Wave/WaveTop/index.tsx, docs/src/components/Wave/WaveTop/styles.module.css, docs/src/components/Wave/WaveTop/wave.tsx, docs/src/components/Wave/WaveTop/waves.tsx, docs/src/css/colors.css, docs/src/css/overrides.css, docs/src/hooks/usePageType.tsx, docs/src/hooks/useScreenSize.tsx, docs/src/pages/index.tsx, docs/src/pages/styles.module.css
=> docs: Add landing page

README.md
As discussed internally, adding a quickstart with running LLMs to the README - #17
=> docs: Add a quickstart guide for Llama

android/src/main/java/com/swmansion/rnexecutorch/OCR.kt, android/src/main/java/com/swmansion/rnexecutorch/RnExecutorchPackage.kt, android/src/main/java/com/swmansion/rnexecutorch/models/ocr/Detector.kt, android/src/main/java/com/swmansion/rnexecutorch/models/ocr/RecognitionHandler.kt, android/src/main/java/com/swmansion/rnexecutorch/models/ocr/Recognizer.kt, android/src/main/java/com/swmansion/rnexecutorch/models/ocr/utils/CTCLabelConverter.kt, android/src/main/java/com/swmansion/rnexecutorch/models/ocr/utils/Constants.kt, android/src/main/java/com/swmansion/rnexecutorch/models/ocr/utils/DetectorUtils.kt, android/src/main/java/com/swmansion/rnexecutorch/models/ocr/utils/RecognizerUtils.kt, android/src/main/java/com/swmansion/rnexecutorch/utils/Fetcher.kt, android/src/main/java/com/swmansion/rnexecutorch/utils/ImageProcessor.kt
=> feat: ocr(android)

docs/docs/benchmarks/_category_.json, docs/docs/computer-vision/useObjectDetection.md, docs/docs/computer-vision/useStyleTransfer.md, docs/docs/hookless-api/ExecutorchModule.md, docs/docs/hookless-api/LLMModule.md, docs/docs/hookless-api/ObjectDetectionModule.md, docs/docs/hookless-api/StyleTransferModule.md, docs/docs/hookless-api/_category_.json, docs/docs/module-api/_category_.json, docs/docs/utils/_category_.json, docs/docs/utils/list-downloaded-resources.md
Add listDownloadedFiles and listDownloadedModels documentation
=> docs: Add listDownloadedFiles and listDownloadedModels documentation

android/src/main/java/com/swmansion/rnexecutorch/ETModule.kt, android/src/main/java/com/swmansion/rnexecutorch/utils/ArrayUtils.kt, android/src/main/java/com/swmansion/rnexecutorch/utils/TensorUtils.kt, ios/RnExecutorch/ETModule.mm, ios/RnExecutorch/models/BaseModel.h, ios/RnExecutorch/models/BaseModel.mm, lefthook.yml, src/hooks/general/useExecutorchModule.ts, src/hooks/useModule.ts, src/modules/general/ExecutorchModule.ts, src/native/NativeETModule.ts, src/native/RnExecutorchModules.ts, src/types/common.ts, third-party/ios/ExecutorchLib/ExecutorchLib.xcodeproj/project.pbxproj, third-party/ios/ExecutorchLib/ExecutorchLib/Exported/ETModel.h, third-party/ios/ExecutorchLib/ExecutorchLib/Exported/ETModel.mm, third-party/ios/ExecutorchLib/ExecutorchLib/Utils.hpp
=> feat: Make third-party/ExecuTorchLib's forward() accept multiple inputs

android/src/main/java/com/swmansion/rnexecutorch/models/BaseModel.kt, android/src/main/java/com/swmansion/rnexecutorch/utils/ArrayUtils.kt, src/SpeechToTextController.ts
=> fix: Remove duplicated native function in ArrayUtils.kt

docs/docs/hookless-api/LLMModule.md, docs/docs/llms/useLLM.md
Add LLM messageHistory documentation
=> docs: Add LLM messageHistory

examples/computer-vision/screens/OCRScreen.tsx, examples/computer-vision/screens/VerticalOCRScreen.tsx
=> design: change design of displaying ocr results

examples/speech-to-text/screens/SpeechToTextScreen.tsx, src/hooks/natural_language_processing/useSpeechToText.ts
=> changed isModelReady to isReady

examples/computer-vision/package.json, examples/computer-vision/yarn.lock, examples/llama/package.json, examples/llama/yarn.lock, examples/speech-to-text/package.json, examples/speech-to-text/yarn.lock, package.json
Bump react-native-executorch version to 0.3.0
=> chore: Bump react-native-executorch version to 0.3.0

README.md, docs/docs/fundamentals/getting-started.md
=> docs: add note about new architecture in readme and docs

README.md, docs/docs/fundamentals/getting-started.md, package.json, yarn.lock
=> fix: make react-native-audio-api a peer dependency

package.json
Currently, we have react and react-native listed as a dependency in package.json. We also have it listed in devDependencies, which makes the yarn v1 fail when installing the package. Fixes #121
=> fix: Make yarn v1 work with react-native-executorch

android/src/main/java/com/swmansion/rnexecutorch/models/BaseModel.kt, android/src/main/java/com/swmansion/rnexecutorch/models/StyleTransferModel.kt, android/src/main/java/com/swmansion/rnexecutorch/models/classification/ClassificationModel.kt, android/src/main/java/com/swmansion/rnexecutorch/models/objectDetection/SSDLiteLargeModel.kt, android/src/main/java/com/swmansion/rnexecutorch/models/ocr/Detector.kt, android/src/main/java/com/swmansion/rnexecutorch/models/ocr/Recognizer.kt, android/src/main/java/com/swmansion/rnexecutorch/models/ocr/VerticalDetector.kt, android/src/main/java/com/swmansion/rnexecutorch/models/speechToText/BaseS2TDecoder.kt, android/src/main/java/com/swmansion/rnexecutorch/models/speechToText/MoonshineEncoder.kt, android/src/main/java/com/swmansion/rnexecutorch/models/speechToText/WhisperEncoder.kt
Remove abstract pre/postprocess methods from BaseModel in native Android code. The methods are always called on concrete classes so it's not necessary for them to be abstract.
=> Remove abstract pre/postprocess from BaseModel

examples/speech-to-text/screens/SpeechToTextScreen.tsx
… in Text component
There was an unnecessary Text zRXW within View in this file. That was causing the error like Text should be rendered within the Text Component.
=> fix: remove redundant text from speech-to-text example app

.github/workflows/build-android-llama-example.yml, .github/workflows/build-ios-llama-example.yml
Adds Llama demo app build for Android to the CI. Also makes some performance improvements by prevending duplicate build runs within the same branch.
=> ci: Add Android llama demo app build check

docs/docs/llms/useLLM.md, docs/docusaurus.config.js
=> docs: added trailing slashes to urls to fix seo indexing

README.md, docs/docs/llms/useLLM.md
- Changed a word from "two examples" to "few examples", so it makes sense. Few is better than three, so it's foolproof longer.
- Changed method name in `useLLM` docs, I think `runInference` is an old name for `generate` and you forgot to change it.
=> docs: Update docs

examples/speech-to-text/screens/SpeechToTextScreen.tsx, src/controllers/SpeechToTextController.ts, src/native/RnExecutorchModules.ts
Currently, the native module accepts two params, namely tokens to decode and a flag whether we should skip special tokens. The _TokenizerModule wrapper's decode called Tokenizer.decode with just the tokens to decode param, resulting in wrong parameters being passed to native side. This PR solves that problem.
=> fix: pass skipSpecialTokens param to Tokenizer in _TokenizerModule

.github/ISSUE_TEMPLATE/bug-report.yml
Remove the mandatory snack or reproduction repository from the bug report issue template.
=> chore: remove mandatory snack or repro repo link in bug reports

src/Error.ts
When non-ET error was passed to `getError()` function it resulted in Undefined error. I've met this example when I had not enough space on the device to download the model
=> fix: error handling

docs/docs/fundamentals/getting-started.md, docs/docs/llms/useLLM.md, docs/src/pages/index.tsx
=> Improve LLMs SEO

docs/docusaurus.config.js, docs/package.json, docs/src/theme/CodeBlock/highlighting-dark.js, docs/src/theme/CodeBlock/highlighting-light.js, docs/src/theme/MDXComponents/Details.js, docs/tsconfig.json, docs/yarn.lock
Ci wont work until t-rex is bumped
Web, please also run your docs and test if everything looks okay.
=> docs: Bump t-rex to stable with Docusaurus 3.7

examples/text-embeddings/package.json
Move react-native-executorch dependency from `devDependencies` to `dependencies`
=> chore: Move react-native-executorch dependency

package.json
This PR changes the configuration of the config to 'modules' instead of 'all', since we don't generate code for native Fabric components. 
See https://reactnative.dev/docs/the-new-architecture/using-codegen#configuring-codegen
=> fix: set codegen config type property to 'modules' instead of 'all'

common/rnexecutorch/host_objects/ModelHostObject.h, common/rnexecutorch/jsi/JsiHostObject.h
Make the model host function installation generic, so that you can easily introduce additional methods that resolve with a promise.
#255
=> fix: make the host function installation generic

packages/react-native-executorch/package.json, yarn.lock
We don't use it anywhere in the library - artifact of the past.
=> Remove react-native-live-audio-strem dependency from the library.

README.md
No testing needed
Not applicable
Not applicable
=> Remove Product Hunt badge & little improvement to installation

packages/react-native-executorch/common/rnexecutorch/host_objects/ModelHostObject.h
Remove a dangling reference when handling exceptions in forward method in native C++.
=> fix: remove a dangling reference exception handling 

packages/react-native-executorch/common/rnexecutorch/RnExecutorchInstaller.h, packages/react-native-executorch/common/rnexecutorch/TypeConstraints.h, packages/react-native-executorch/common/rnexecutorch/host_objects/ModelHostObject.h, packages/react-native-executorch/common/rnexecutorch/models/BaseModel.cpp, packages/react-native-executorch/common/rnexecutorch/models/BaseModel.h, packages/react-native-executorch/common/rnexecutorch/models/image_segmentation/ImageSegmentation.cpp, packages/react-native-executorch/common/rnexecutorch/models/style_transfer/StyleTransfer.cpp, packages/react-native-executorch/src/hooks/useNonStaticModule.ts, packages/react-native-executorch/src/index.tsx, packages/react-native-executorch/src/modules/BaseNonStaticModule.ts, packages/react-native-executorch/src/modules/computer_vision/ImageSegmentationModule.ts, packages/react-native-executorch/src/modules/computer_vision/StyleTransferModule.ts
The garbage collector doesn't see the memory allocated on the heap by host objects, so we need to notify it of the memory occupied by ET modules, otherwise it will take a long time before freeing it. We set the memory pressure to the size of the .pte file of the model (an underestimate of the true size) and add a host function to release the module memory.
#254
=> feat: add memory pressure to models and allow freeing their memory

packages/react-native-executorch/common/rnexecutorch/host_objects/ModelHostObject.h, packages/react-native-executorch/common/rnexecutorch/models/BaseModel.cpp, packages/react-native-executorch/common/rnexecutorch/models/BaseModel.h, packages/react-native-executorch/react-native-executorch.podspec, packages/react-native-executorch/src/native/NativeClassification.ts, packages/react-native-executorch/src/native/RnExecutorchModules.ts
It caused crashes when unloading model. Names didn't match
=> fix: Rename unload cpp function

packages/react-native-executorch/src/modules/BaseModule.ts, packages/react-native-executorch/src/modules/natural_language_processing/TextEmbeddingsModule.ts, packages/react-native-executorch/src/modules/natural_language_processing/TokenizerModule.ts
Tested in CV object detection - it works
=> Enable passing extra args to load function in classes derived from BaseModule

docs/docs/natural-language-processing/useTextEmbeddings.md, docs/docs/typescript-api/TextEmbeddingsModule.md, packages/react-native-executorch/android/src/main/java/com/swmansion/rnexecutorch/TextEmbeddings.kt, packages/react-native-executorch/android/src/main/java/com/swmansion/rnexecutorch/models/TextEmbeddings/TextEmbeddingsModel.kt, packages/react-native-executorch/ios/RnExecutorch/TextEmbeddings.mm, packages/react-native-executorch/ios/RnExecutorch/models/text_embeddings/TextEmbeddingsModel.h, packages/react-native-executorch/ios/RnExecutorch/models/text_embeddings/TextEmbeddingsModel.mm, packages/react-native-executorch/src/hooks/natural_language_processing/useTextEmbeddings.ts, packages/react-native-executorch/src/modules/natural_language_processing/TextEmbeddingsModule.ts, packages/react-native-executorch/src/native/NativeTextEmbeddings.ts
Some models do mean pooling, some don't. We can set flag to take that into account - we should set this flag in all presets for our models while completing: https://github.com/software-mansion/react-native-executorch/issues/359
#353
=> feat: Flag for mean pooling text embeddings

packages/react-native-executorch/src/utils/ResourceFetcher.ts
When loading two models using require the 2nd would overwrite the 1st one, cause this function produced the same name for them. It worked for remote URLs that were different in path part (the one divided by slashes), but locally loaded files only differ by GET params, that were cut off by split('?')[0]. This fixes it.
It might be considered breaking change in a sense it may change names of models in the current app, so models will redownload
=> fix: Fix function in resource fetcher that produced the same name for different requires in development mode

.cspell-wordlist.txt, .eslintrc.js, docs/docs/computer-vision/useClassification.md, docs/docs/computer-vision/useImageSegmentation.md, docs/docs/computer-vision/useOCR.md, docs/docs/computer-vision/useObjectDetection.md, docs/docs/computer-vision/useStyleTransfer.md, docs/docs/computer-vision/useVerticalOCR.md, docs/docs/fundamentals/loading-models.md, docs/docs/natural-language-processing/useLLM.md, docs/docs/natural-language-processing/useSpeechToText.md, docs/docs/natural-language-processing/useTextEmbeddings.md, docs/docs/natural-language-processing/useTokenizer.md, docs/docs/typescript-api/SpeechToTextModule.md, lefthook.yml, package.json, yarn.lock
Added eslint markdown plugin to format code blocks in docs using our eslint config.
I corrected critical errors (mostly "...") so blocks are correctly formatted.
It also generates a lot of new warnings (`no-unused-vars`) - we can safely ignore most of them, but when you produce new piece of docs you should monitor them, if they can be safely ignored, or did you misspell the variable you declared before that. We cannot enable `no-undef-vars` because it produces too many warnings (every JSX tag etc.), so we have to rely on those `no-unused-vars` warnings:
=> docs: Added eslint markdown plugin and fixed all critical errors

.cspell-wordlist.txt, CONTRIBUTING.md, RELEASE.md
Add RELEASE.md na CONTRIBUTING.md files.
=> added RELEASE.md and CONTRIBUTING.md files

.eslintrc.js, packages/react-native-executorch/src/common/Logger.ts
Changes:
- Added a new override to enforce the no-console rule for files in `react-native-executorch/src`, excluding Logger.ts
- Added a static log method to Logger class
=> feat: enable 'no-console' lint rule for executorch src except Logger, add Logger.log method

apps/speech-to-text/package.json, yarn.lock
Prevents crash in speech to text app.
Closes #467 
Currently, the app crashes after clicking `Transcribe with URL`. Bump of `react-native-audio-api` prevents this crash.
Test before and after the change. You should see that after installing node modules with updated package app does not crash.
#467
=> Update `react-native-audio-api` dependency to prevent demo app crash

src/Error.ts
Fix error messages formatting
from
```
[Error: UndefinedErrorModuleNotLoaded]
```
to:
```
[Error: MultilingualConfiguration]
```
=> fix: error messages formatting

packages/react-native-executorch/src/utils/ResourceFetcher.ts
Previously, if resources were already downloaded, callback could remain at 0. 
Now, always before returning ResourceFetcher sets the callback to 1.
=> Resource Fetcher Set Callback to 1 when download is Finished

packages/react-native-executorch/src/Error.ts
Fix error messages formatting
from
```
[Error: UndefinedErrorModuleNotLoaded]
```
to:
```
[Error: MultilingualConfiguration]
```
=> fix: error messages formatting (#476)

packages/react-native-executorch/common/rnexecutorch/Log.h
Currently some of the functions are defined in the header file and they are not inline, resulting in duplicate symbols when including in multiple files. This PR makes those functions inline, fixing that error.
=> fix: inline logging functions to prevent ODR violation

docs/docs/02-hooks/02-computer-vision/useVerticalOCR.md
In parameter description of `useVerticalOCR`, fixes `language` position so it's nested under `model`.
=> docs: fix parameter description formatting in OCR docs

packages/react-native-executorch/package.json
Commit fea6dbfa25bc introduced a modification to `package.json` that caused an issue during the pre-commit hook.
Specifically, after this change, running `yarn typecheck` on any modified `.ts` file within `packages/react-native-executorch` would emit a corresponding `.js` file.
Adding the `--noEmit` flag to the `yarn typecheck` command,  prevents these extra files from being created.
=> Fix: stop yarn typecheck from creating `.js` files inside project. 

packages/react-native-executorch/src/constants/modelUrls.ts, packages/react-native-executorch/src/constants/ocr/models.ts
This PR aligns urls to the models so they match the v0.5.0 version. For every models, except the ones introduced in v0.5.0, a tag on a respective HuggingFace repo has been created.
=> feat: update modelUrls to match v0.5.0 version

packages/react-native-executorch/src/utils/ResourceFetcherUtils.ts
Fixes a resource fetcher bug, which prevented from actually loading downloaded models without internet connection. 
Issue occurred due to the wrong error handling in the process of fetching head (to get the content length) of the resource. 
Closes #563
=> Fix: Resource Fetcher not loading downloaded models

.cspell-wordlist.txt, packages/react-native-executorch/src/utils/SpeechToTextModule/ASR.ts
Adds word `probs` to cspell to be recognized and renames two variables to avoid naming clash inside a function.
Check if warnings are not present
#536
=> Add word to cspell and fix naming clash

packages/react-native-executorch/common/rnexecutorch/RnExecutorchInstaller.cpp, packages/react-native-executorch/common/rnexecutorch/data_processing/Numerical.cpp, packages/react-native-executorch/common/rnexecutorch/host_objects/ModelHostObject.h
the c++ 20  `std::format` relies on c++ 17 `std::to_char` which was introduced later in libc++ effectively meaning that no build with target < iOS 16.3 can use `std::format`, (see [this](https://developer.apple.com/xcode/cpp/#c++17))
The simplest solution is to basically remove all `std::format` for now. 
The more future-realistic solutions could be considered. 
To see the more verbose discussion  go to #570.
=> Remove `std::format` from c++ code to support _LIBCPP_STD_VER < 20

RELEASE.md
From what I understand, currently, RNE does not use jitpack. This PR removes bullet points that mentioned jitpack. Also removed a point with a release tracker, as I saw that there is no such issue for `0.6.0` release.
Closes #527
=> Remove jitpack from RELEASE.md

packages/react-native-executorch/android/CMakeLists.txt, packages/react-native-executorch/common/rnexecutorch/TokenizerModule.cpp, packages/react-native-executorch/common/rnexecutorch/models/ocr/CTCLabelConverter.h, packages/react-native-executorch/common/rnexecutorch/models/ocr/utils/RecognitionHandlerUtils.cpp, packages/react-native-executorch/common/rnexecutorch/models/text_to_image/Scheduler.h, packages/react-native-executorch/common/rnexecutorch/models/text_to_image/TextToImage.cpp, packages/react-native-executorch/common/runner/irunner.h, packages/react-native-executorch/common/runner/runner.cpp, packages/react-native-executorch/common/runner/runner.h, packages/react-native-executorch/common/runner/sampler.h, packages/react-native-executorch/common/runner/stats.h, packages/react-native-executorch/common/runner/text_decoder_runner.h, packages/react-native-executorch/common/runner/text_prefiller.h, packages/react-native-executorch/common/runner/text_token_generator.h, packages/react-native-executorch/common/runner/util.h
Fixes to remove warnings when compiling react-native-executorch:
- removed `ET_EXPERIMENTAL` markings from classes in `/packages/react-native-executorch/common/runner`
- suppressed deprecation warnings from third-party headers
- eliminated unused variables
- untangled recursive variable initialization
Closes #498
=> chore: Get rid of compiler warnings
